### ISSUE TITLE
How to use in standalone mode?

### ISSUE THREAD

**Issue by LostKoder** [matthiasnoback/symfony-console-form#24]

**Comment by matthiasnoback** [comment]
Please be a bit more specific. What does stand-alone mean in your situation?

**Comment by LostKoder** [comment]
Consider I have a console application which does not belongs to Symfony framework and it simply uses `symfony/console` component. How can I use this component in such situation?

**Comment by matthiasnoback** [comment]
Okay, that might be some work. It's doable, but you'd have to replicate all the logic from the Bundle directory basically. If you know Symfony, you can figure it out I guess :)

**Comment by LostKoder** [comment]
I think we should decouple bundle and standalone versions to cover more use cases.

**Comment by matthiasnoback** [comment]
I totally agree that you may consider this not to be ideal ;) Something like a container-interop/service provider approach would be very useful. If you make something, I'll happily merge it (as long as it follows the same principles, i.e. extendability using collections of transformers and helpers.

**Comment by LostKoder** [comment]
Good, I will schedule a time for it.

**Comment by matthiasnoback** [comment]
Very nice, thanks for taking an interest :)

**Comment by matthiasnoback** [comment]
Hey @LostKoder, is this issue still relevant?

**Comment by LostKoder** [comment]
hey, yep.

**Comment by matthiasnoback** [comment]
Okay, but are you planning to work on it, @LostKoder ? :)

**Comment by LostKoder** [comment]
Of course, I was a little busy previous months. It's my pleasure to work on it!

**Comment by LostKoder** [comment]
Console FormHelper class has very long dependency tree. What's your idea to handle it @matthiasnoback  ?

**Comment by matthiasnoback** [comment]
Hey @LostKoder, you need to be more clear about what you write ;) I have no idea what you mean by this.

**Comment by LostKoder** [comment]
In order to integrate `form component` with `console application`  we need to instantiate `Matthias\SymfonyConsoleForm\Console\Helper\FormHelper` and plug it in our application with `$app->setHelperSet()` method, right? 

Mentioned class has long dependency tree which is hard to provide and instantiate.

What's your idea about handling such case without symfony container service definitions @matthiasnoback?

**Comment by matthiasnoback** [comment]
Hmm, yes; well, it's basically everything that's inside `services.yml`, right? ;) It would be an option to introduce a factory for the `FormHelper`, which can be used by the bundle too. It would require some careful analysis, since it should still be possible to use DI tags for instance.

**Comment by matthiasnoback** [comment]
Closing this now, feel free to reopen it when you have more on this.
