### ISSUE TITLE
call Form command from within another command

### ISSUE THREAD

**Issue by craigh** [matthiasnoback/symfony-console-form#4]
I would like to call an `InteractiveFormCommand` from within another command like:

``` php
// myform:meta
    protected function execute(InputInterface $xinput, OutputInterface $output)
    {
        $command = $this->getApplication()->find('myform:test');
        $input = new ArrayInput(array('command' => 'myform:test'));
        $code = $command->run($input, $output);
        if ($code !== 0) {
            $output->writeln("<error>failed</error>");
            return;
        }
    }
```

but the command fails to set the data in the form 

``` Shell
$ php app/console myform:meta
  [LogicException]                       
  For some reason, no form data was set  
```

The command works fine if I just run (as normal)

``` Shell
$ php app/console myform:test
```

which works as expected.

do I need to do something differently or is this expected?

thank you for your ongoing patience :smile:

**Comment by matthiasnoback** [comment]
I don't think this would work (at least I didn't test this use case). 
You could always use it in each command in a stand-alone way:

``` php
$formType = ...;
$this->getHelper('form')->interactUsingForm($formType, $input, $output);
```

**Comment by craigh** [comment]
thank you. that is a much better method :smile:

**Comment by matthiasnoback** [comment]
Nice! Thanks. Hope this library turns out to be helpful in your situation.
