### ISSUE TITLE
Formatting issue when editing some existing data

### ISSUE THREAD

**Issue by tarlepp** [matthiasnoback/symfony-console-form#45]
First of all, really big thanks to you for this library - it's awesome.

I noticed that existing `default` value is shown as `<default>admin</default>` with Symfony 5.2 - not sure which Symfony version caused that change.

![image](https://user-images.githubusercontent.com/595561/107074304-3a6e0480-67f1-11eb-9e30-62817b866c24.png)

**Comment by matthiasnoback** [comment]
Thanks!
I'm not actually using this library currently, but maybe you can investigate this further? I'd be happy to review and merge your PR.

**Comment by matthiasnoback** [comment]
Fixed by #47 I decided to remove all custom formatting and rely on Symfony defaults. A lot of the existing code could be removed too :)

**Comment by tarlepp** [comment]
> Fixed by #47 I decided to remove all custom formatting and rely on Symfony defaults. A lot of the existing code could be removed too :)

Yeah, that sounds the proper way to handle this - those Symfony styles should not change so often, most like never - and if those are changed I think that can be done only on Symfony major version update - so this solution should be quite safe.

**Comment by matthiasnoback** [comment]
Thanks, glad you agree! It was a good moment to modernize a bit. I hope everything still works for everyone :)

**Comment by tarlepp** [comment]
I'll update to latest release in next week, and share the results after that - I did take a quick look of those code changes and there should not be any BC stuff.

**Comment by matthiasnoback** [comment]
Yes, I think so. It is funny how much still works after all those years!

**Comment by tarlepp** [comment]
@matthiasnoback just updated to `5.0.0` and it seems to work like a charm! Thank you for this great library!

**Comment by matthiasnoback** [comment]
Great, thanks for checking, and thanks for letting me know! If I may ask, what do you use it for?

**Comment by tarlepp** [comment]
Could you ping me on Symfony Slack - so that we could continue this conversation there? My nick there is tarlepp

**Comment by matthiasnoback** [comment]
Oh, I'm not actually on that Slack.

**Comment by tarlepp** [comment]
> Great, thanks for checking, and thanks for letting me know! If I may ask, what do you use it for?

So basically I have multiple API projects where I need to use some user / api-key / etc. management from the shell (on that point when there isn't yet frontend implementation for those) - So I have used this library for years and I'm really happy with it - Sure I could use pure Symfony console component tools to do the same, but this library is doing all what I need and it's simple to use.

And those projects I don't use Symfony forms for anything else than those couple of console commands - just to make clear that I'm not using forms on API :D

**Comment by matthiasnoback** [comment]
That's really cool, thanks for explaining this!
